development:
  adapter: postgresql
  database: lovitmart_development
  pool: 5
  timeout: 5000
  username: bill
  password: bill
test:
  adapter: postgresql
  database: loveitmart_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: loveitmart_production
  pool: 5
  timeout: 500