# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c12864a1ffebc83fee5396caf71e7534465c9162ea3bd617b11f7b1ab6c00ab465657870e5fd27becbac08d686022a9886f925cc130edbbcef93365db18beac4

test:
  secret_key_base: 8d69ca805325a7a5e9eb85b031393aef84d0e8b683a7eb677587313a0ffa2975552a0b6761b6e7f3e4a7a9b322010176320324a5ddbf1d6244b633a1d972f9d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
